name: avatarmakercopy
description: "A new Flutter project."
publish_to: 'none'  # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'  # Updated SDK version constraint

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  model_viewer_plus: ^1.5.0
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.5
  fl_chart: ^0.62.0
  provider: ^6.0.1
  get: ^4.6.5
  path_provider: ^2.0.15
  image_gallery_saver: ^2.0.3
  flutter_secure_storage: ^9.0.0
  jwt_decode: ^0.3.1
  shared_preferences: ^2.0.15
  webview_flutter: ^3.0.4
  toggle_switch: ^2.0.1
  http: ^0.13.3
  connectivity: ^3.0.6
  file_picker: ^8.0.3
  dash_chat_2: 0.0.18
  chat_gpt_sdk: 2.2.5
  flutter_tts: ^3.3.3
  camera:
  google_ml_kit: ^0.18.0
  google_mlkit_object_detection: 0.13.0


dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
flutter:

  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
    - assets/avatar/
    - assets/avatar/body/
    - assets/avatar/eyes/
    - assets/avatar/nose/
    - assets/avatar/mouth/
    - assets/avatar/head/hair/
    - assets/avatar/head/hair/long/
    - assets/avatar/head/hair/short/
    - assets/avatar/head/accessories/
    - assets/avatar/facial hair/
    - assets/avatar/accessories/
    - assets/avatar/clothing/
    - assets/
    - assets/user_profile.jpg
    - assets/vocal.jpg
    - assets/vocal.svg
    - assets/iframe.html
    - assets/images/
    - assets/svg/

  fonts:
      - family: IBMPlexSans
        fonts:
          - asset: assets/fonts/IBMPlexSans-Bold.ttf
            weight: 900
          - asset: assets/fonts/IBMPlexSans-Bold.ttf
            weight: 800
          - asset: assets/fonts/IBMPlexSans-Bold.ttf
            weight: 700
          - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/IBMPlexSans-Medium.ttf
            weight: 500
          - asset: assets/fonts/IBMPlexSans-Regular.ttf
            weight: 400
          - asset: assets/fonts/IBMPlexSans-Light.ttf
            weight: 300
          - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/IBMPlexSans-Thin.ttf
            weight: 100

